# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'sparkair-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sparkair-ios
  pod 'ObjectMapper'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'
  pod 'Firebase/Storage'
  pod 'SnapKit'
  pod 'Hex'
end
